name: Update Dependencies
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  flake-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        input:
          - flake-utils
          - nixpkgs
          - pre-commit-hooks
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Update ${{ matrix.input }}
        uses: ./
        with:
          dependency: ${{ matrix.input }}
          pull-request-token: ${{ steps.generate_token.outputs.token }}
          pull-request-author: "Phillip Ground <cpcloudbot@gmail.com>"
          pull-request-labels: dependencies,autorebase:opt-in
          automerge: true
